# This is a basic workflow to help you get started with Actions

name: 可视化自动构建

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the chap0x04 branch
  push:
    branches: [ chap0x04 ]
  pull_request:
    branches: [ chap0x04 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  _自动构建:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 必要软件安装
        run: sudo apt update && sudo apt upgrade -y && sudo apt install shellcheck imagemagick p7zip-full -y

      # Runs a set of commands using the runners shell
      - name: 脚本演示
        run: |
          cd ./chap0x04/sh
          wget "https://raw.githubusercontent.com/c4pr1c3/LinuxSysAdmin/master/exp/chap0x04/worldcupplayerinfo.tsv"
          wget "https://raw.githubusercontent.com/c4pr1c3/LinuxSysAdmin/master/exp/chap0x04/web_log.tsv.7z"
          7z x web_log.tsv.7z
          ls -lh
          chmod +x ./task1.sh ./task2.sh ./task3.sh
          ls -lh
          ./task1.sh -h
          ./task2.sh -h
          ./task2.sh -s
          ./task2.sh -p
          ./task2.sh -n longest
          ./task2.sh -n shortest
          ./task2.sh -a oldest
          ./task2.sh -a youngest
          ./task3.sh -h
          ./task3.sh -t
          ./task3.sh -t ip
          ./task3.sh -u
          ./task3.sh -s
          ./task3.sh -e
          ./task3.sh -c "/history/history.html"